// This file is automatically generated. Do not edit it directly.
// Modo OFFLINE: sempre usa dados mockados
import { mockSupabase } from '@/integrations/supabase/mock';
import { initializeDemoData } from '@/integrations/supabase/demo/initDemoData';

// Carrega DADOS DEMO e ativa cliente mock
initializeDemoData();

// Cliente Supabase fixo no mock (sem dependências externas)
export const supabase: any = mockSupabase;
